baseURL = "https://simonrichardson.github.io/"
languageCode = "en-us"
title = "Simon Richardson"

[params]
  Subtitle = "Software Engineer"
  GithubID = "SimonRichardson"
  TwitterID = "SimonRichardson"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright Me 2016. Powered by Hugo."